NDA/config/routes.rb
Rails.application.routes.draw do
  resources :natural_disaster_categories
  resources :disasters
  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/natural_disaster_categories')
end

NDA/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

NDA/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :disaster 
end

NDA/app/models/disaster.rb
class Disaster < ApplicationRecord
  belongs_to :natural_disaster_category
  has_many :comments
end

NDA/app/models/natural_disaster_category.rb
class NaturalDisasterCategory < ApplicationRecord
  has_many :disasters
end

NDA/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

NDA/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :content)
    end
end

NDA/app/controllers/disasters_controller.rb
class DisastersController < ApplicationController
  before_action :set_disaster, only: [:show, :edit, :update, :destroy]

  # GET /disasters
  # GET /disasters.json
  def index
    @disasters = Disaster.all
  end

  # GET /disasters/1
  # GET /disasters/1.json
  def show
  end

  # GET /disasters/new
  def new
    @disaster = Disaster.new
  end

  # GET /disasters/1/edit
  def edit
  end

  # POST /disasters
  # POST /disasters.json
  def create
    @disaster = Disaster.new(disaster_params)

    respond_to do |format|
      if @disaster.save
        format.html { redirect_to @disaster, notice: 'Disaster was successfully created.' }
        format.json { render :show, status: :created, location: @disaster }
      else
        format.html { render :new }
        format.json { render json: @disaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disasters/1
  # PATCH/PUT /disasters/1.json
  def update
    respond_to do |format|
      if @disaster.update(disaster_params)
        format.html { redirect_to @disaster, notice: 'Disaster was successfully updated.' }
        format.json { render :show, status: :ok, location: @disaster }
      else
        format.html { render :edit }
        format.json { render json: @disaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disasters/1
  # DELETE /disasters/1.json
  def destroy
    @disaster.destroy
    respond_to do |format|
      format.html { redirect_to disasters_url, notice: 'Disaster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disaster
      @disaster = Disaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disaster_params
      params.require(:disaster).permit(:title, :photo_url, :description, :preparation)
    end
end

NDA/app/controllers/natural_disaster_categories_controller.rb
class NaturalDisasterCategoriesController < ApplicationController
  before_action :set_natural_disaster_category, only: [:show, :edit, :update, :destroy]

  # GET /natural_disaster_categories
  # GET /natural_disaster_categories.json
  def index
    @natural_disaster_categories = NaturalDisasterCategory.all
  end

  # GET /natural_disaster_categories/1
  # GET /natural_disaster_categories/1.json
  def show
    @natural_disaster_categories = NaturalDisasterCategory.find(params[:id])
    @disaster = Disaster.find(params[:id])

      respond_to do |format|
        format.html {render :show}
        format.json {render json: @disaster}
  end
end

  # GET /natural_disaster_categories/new
  def new
    @natural_disaster_category = NaturalDisasterCategory.new
  end

  # GET /natural_disaster_categories/1/edit
  def edit
  end

  # POST /natural_disaster_categories
  # POST /natural_disaster_categories.json
  def create
    @natural_disaster_category = NaturalDisasterCategory.new(natural_disaster_category_params)

    respond_to do |format|
      if @natural_disaster_category.save
        format.html { redirect_to @natural_disaster_category, notice: 'Natural disaster category was successfully created.' }
        format.json { render :show, status: :created, location: @natural_disaster_category }
      else
        format.html { render :new }
        format.json { render json: @natural_disaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /natural_disaster_categories/1
  # PATCH/PUT /natural_disaster_categories/1.json
  def update
    respond_to do |format|
      if @natural_disaster_category.update(natural_disaster_category_params)
        format.html { redirect_to @natural_disaster_category, notice: 'Natural disaster category was successfully updated.' }
        format.json { render :show, status: :ok, location: @natural_disaster_category }
      else
        format.html { render :edit }
        format.json { render json: @natural_disaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /natural_disaster_categories/1
  # DELETE /natural_disaster_categories/1.json
  def destroy
    @natural_disaster_category.destroy
    respond_to do |format|
      format.html { redirect_to natural_disaster_categories_url, notice: 'Natural disaster category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_natural_disaster_category
      @natural_disaster_category = NaturalDisasterCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def natural_disaster_category_params
      params.require(:natural_disaster_category).permit(:title, :photo_url)
    end
end

NDA/app/helpers/application_helper.rb
module ApplicationHelper
end

NDA/app/helpers/comments_helper.rb
module CommentsHelper
end

NDA/app/helpers/disasters_helper.rb
module DisastersHelper
end

NDA/app/helpers/natural_disaster_categories_helper.rb
module NaturalDisasterCategoriesHelper
end

NDA/app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NDA/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

NDA/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

NDA/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

NDA/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

NDA/app/views/disasters/_form.html.erb
<%= form_for(disaster) do |f| %>
  <% if disaster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(disaster.errors.count, "error") %> prohibited this disaster from being saved:</h2>

      <ul>
      <% disaster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :preparation %>
    <%= f.text_area :preparation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NDA/app/views/disasters/edit.html.erb
<h1>Editing Disaster</h1>

<%= render 'form', disaster: @disaster %>

<%= link_to 'Show', @disaster %> |
<%= link_to 'Back', disasters_path %>

NDA/app/views/disasters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disasters</h1>

<table>
  <thead>
    <ul>
      <li>Title</li>
      <li>Photo url</li>
      <li>Description</li>
      <li>Preparation</li>
      <!-- <li colspan="3"></li> -->
    </ul>
  </thead>

  <tbody>
    <% @disasters.each do |disaster| %>
      <tr>

        <td><%= disaster.title %></td>
        <td><%= disaster.photo_url %></td>
        <td><%= disaster.description %></td>
        <td><%= disaster.preparation %></td>
        <td><%= link_to 'Show', disaster %></td>
        <td><%= link_to 'Edit', edit_disaster_path(disaster) %></td>
        <td><%= link_to 'Destroy', disaster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disaster', new_disaster_path %>

NDA/app/views/disasters/new.html.erb
<h1>New Disaster</h1>

<%= render 'form', disaster: @disaster %>

<%= link_to 'Back', disasters_path %>

NDA/app/views/disasters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @disaster.title %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @disaster.photo_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @disaster.description %>
</p>

<p>
  <strong>Preparation:</strong>
  <%= @disaster.preparation %>
</p>

<%= link_to 'Edit', edit_disaster_path(@disaster) %> |
<%= link_to 'Back', disasters_path %>

NDA/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NDA</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

NDA/app/views/natural_disaster_categories/_form.html.erb
<%= form_for(natural_disaster_category) do |f| %>
  <% if natural_disaster_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(natural_disaster_category.errors.count, "error") %> prohibited this natural_disaster_category from being saved:</h2>

      <ul>
      <% natural_disaster_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NDA/app/views/natural_disaster_categories/edit.html.erb
<h1>Editing Natural Disaster Category</h1>

<%= render 'form', natural_disaster_category: @natural_disaster_category %>

<%= link_to 'Show', @natural_disaster_category %> |
<%= link_to 'Back', natural_disaster_categories_path %>

NDA/app/views/natural_disaster_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Natural Disaster Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Photo url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @natural_disaster_categories.each do |natural_disaster_category| %>
      <tr>
        <td><%= natural_disaster_category.title %></td>
        <td><img src="<%= natural_disaster_category.photo_url %>"></td>
        <td><%= link_to 'Show', natural_disaster_category %></td>
        <td><%= link_to 'Edit', edit_natural_disaster_category_path(natural_disaster_category) %></td>
        <td><%= link_to 'Destroy', natural_disaster_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Natural Disaster Category', new_natural_disaster_category_path %>

NDA/app/views/natural_disaster_categories/new.html.erb
<h1>New Natural Disaster Category</h1>

<%= render 'form', natural_disaster_category: @natural_disaster_category %>

<%= link_to 'Back', natural_disaster_categories_path %>

NDA/app/views/natural_disaster_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @natural_disaster_category.title %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @natural_disaster_category.photo_url %>
</p>

<%= link_to 'Edit', edit_natural_disaster_category_path(@natural_disaster_category) %> |
<%= link_to 'Back', natural_disaster_categories_path %>